# Generated by Django 3.1.7 on 2021-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Cashier',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='booker',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sales_assistant',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
