# Generated by Django 3.1.7 on 2021-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210225_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Cashier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='booker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sales_assistant',
        ),
    ]
