# Generated by Django 3.1.7 on 2021-02-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210227_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default='2021-02-27'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date_create',
            field=models.DateField(blank=True, default='2021-02-27'),
        ),
    ]
