# Generated by Django 3.1.7 on 2021-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210301_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
