# Generated by Django 3.1.7 on 2021-03-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_score_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_product',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='date_create',
            new_name='date_score',
        ),
    ]
