# Generated by Django 3.1.7 on 2021-03-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210301_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='price',
        ),
        migrations.RemoveField(
            model_name='score',
            name='title',
        ),
    ]
